# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/ulid/all/ulid.rbi
#
# ulid-1.4.0

module ULID
  extend ULID::Generator
end
module ULID::Generator
  def encode(input, length); end
  def generate(time = nil, suffix: nil); end
  def generate_bytes(time = nil, suffix: nil); end
  def time_48bit(time = nil); end
end
